## MAT1120 - Obligatorisk oppgave 1 

### Oppgave 1.1
Som et eksempel på to 3x3-matriser $A$ og $B$ der $AB \neq BA$ kan man bruke følgende matriser:
$$ A = \begin{pmatrix}
1 & 2 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
B = \begin{pmatrix}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0
\end{pmatrix}$$ 
Beregner matriseproduktene $AB$ og $BA$ i python:

In [1]:
import numpy as np

# Definer matriser A og B
A = np.array([[1, 2, 0],
              [0, 1, 0],
              [0, 0, 1]])

B = np.array([[0, 1, 0],
              [0, 0, 1],
              [1, 0, 0]])

# Beregn matriseproduktet AB
AB = np.dot(A, B)

# Beregn matriseproduktet BA
BA = np.dot(B, A)

# Skriv ut resultatene
print("Resultat av AB:")
print(AB)

print("Resultat av BA:")
print(BA)

Resultat av AB:
[[0 1 2]
 [0 0 1]
 [1 0 0]]
Resultat av BA:
[[0 1 0]
 [0 0 1]
 [1 2 0]]


Ser at $AB \neq BA$.